package com.example.decide;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.widget.TextView;

import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class MainActivity extends AppCompatActivity {
    private BottomNavigationView botNavView;

    private TextView firstInfo;
    private TextView secondInfo;
    private TextView thirdInfo;
    private TextView fourthInfo;
    private TextView fifthInfo;
    private FirebaseDatabase database = FirebaseDatabase.getInstance();
    private DatabaseReference reference = database.getReference("Info1");
    private DatabaseReference referenceTwo = database.getReference("Info2");
    private DatabaseReference referenceThree = database.getReference("Info3");
    private DatabaseReference referenceFour = database.getReference("Info4");
    private DatabaseReference referenceFive= database.getReference("Info5");
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        firstInfo = findViewById(R.id.text2);
        secondInfo = findViewById(R.id.text3);
        thirdInfo = findViewById(R.id.text4);
        fourthInfo = findViewById(R.id.text5);
        fifthInfo = findViewById(R.id.text6);
        botNavView();
        dataViewOne();
        dataViewTwo();
        dataViewThree();
        dataViewFour();
        dataViewFive();
    }

    public void botNavView() {
        botNavView = findViewById(R.id.navigation_bottom);
        botNavView.setSelectedItemId(R.id.home1);

        botNavView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem menuItem) {
                switch (menuItem.getItemId()) {
                    case R.id.decisions:
                        startActivity(new Intent(getApplicationContext(), Decision.class));
                        return true;
                    case R.id.home1:
                        return true;
                    case R.id.notepad:
                        startActivity(new Intent(getApplicationContext(), Notepad.class));
                        return true;
                }
                return false;
            }
        });
    }

    public void dataViewOne() {
        reference.setValue("Welcome to decision maker a application prioritising in making users decision making easier than ever on general tasks!");
        reference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                firstInfo.setText(value);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }

    public void dataViewTwo() {
        referenceTwo.setValue("There are many ways to navigate within this appication either decision making page or to record a decision generated by typing this update on the notepad page.");
        referenceTwo.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                secondInfo.setText(value);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
    public void dataViewThree() {
        referenceThree.setValue("Not only this within the decision making area you can either choose general decision where you can enter your own general decisions, also choose to enter your own general decisions , or choose features already built such as features, tasks or holiday.");
        referenceThree.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                thirdInfo.setText(value);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
    public void dataViewFour() {
        referenceFour.setValue("Once this is done there are three generate number buttons if you entered , or select two options you should click the generate two options button, if you clicked on three options you should click on generate three buttons selected, if you clicked on four options then you should click on four generated buttons generated.");
        referenceFour.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                fourthInfo.setText(value);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
    public void dataViewFive() {
        referenceFive.setValue("Then click on the notepad to record your results and enjoy your day");
        referenceFive.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                fifthInfo.setText(value);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
}
